bot:
  #TODO: split file locs for test/prod
  photos-directory: /var/dunebot/photo
  pdf-directory: /var/dunebot/pdf
logging:
  level:
    root: error
    ru.trainithard.dunebot: debug
  charset:
    console: UTF-8
    file: UTF-8
  file:
    #TODO: split file locs for test/prod
    name: /var/dunebot/log/dunebot.log
  logback:
    rollingpolicy:
      max-file-size: 10MB

---

spring:
  config:
    activate:
      on-profile: prod
  main:
    web-application-type: none
  datasource:
    url: jdbc:postgresql://db:5432/postgres
    #    todo
    username: sa
    password: sa
    driver-class-name: org.postgresql.Driver
  task:
    scheduling:
      pool:
        size: 2
  sql:
    init:
      mode: never
  liquibase:
    change-log: classpath:changelog.xml

---

spring:
  config:
    activate:
      on-profile: test
  main:
    web-application-type: none
  datasource:
    url: jdbc:h2:mem:testdb;MODE=PostgreSQL;database_to_lower=true;NON_KEYWORDS=KEY,VALUE
    username: sa
    password: password
    driver-class-name: org.h2.Driver

    hikari:
      minimum-idle: 5
  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.H2Dialect
  sql:
    init:
      mode: embedded
      platform: h2
      schema-locations: classpath:schema.sql
bot:
  token: fake_token
  photos-directory: photos
  pdf-directory: pdf
