CREATE TABLE IF NOT EXISTS PLAYERS
(
    ID               BIGSERIAL PRIMARY KEY,
    TELEGRAM_ID      BIGINT      NOT NULL,
    TELEGRAM_CHAT_ID BIGINT      NOT NULL,
    STEAM_NAME       VARCHAR     NOT NULL,
    FIRST_NAME       VARCHAR     NOT NULL,
    LAST_NAME        VARCHAR,
    USER_NAME        VARCHAR,
    CREATED_AT       TIMESTAMPTZ NOT NULL,
    UPDATED_AT       TIMESTAMPTZ,
    CONSTRAINT UNQ_TELEGRAM_ID UNIQUE (TELEGRAM_ID),
    CONSTRAINT UNQ_STEAM_NAME UNIQUE (STEAM_NAME)
);

CREATE TABLE IF NOT EXISTS MATCHES
(
    ID                       BIGSERIAL PRIMARY KEY,
    TELEGRAM_POLL_ID         VARCHAR,
    TELEGRAM_MESSAGE_ID      BIGINT,
    TELEGRAM_CHAT_ID         VARCHAR,
    OWNER_ID                 BIGINT REFERENCES PLAYERS (ID),
    REGISTERED_PLAYERS_COUNT INTEGER     NOT NULL,
    IS_FINISHED              BOOLEAN     NOT NULL DEFAULT FALSE,
    MOD_TYPE                 VARCHAR     NOT NULL,
    CREATED_AT               TIMESTAMPTZ NOT NULL,
    UPDATED_AT               TIMESTAMPTZ,
    CONSTRAINT UNQ_TELEGRAM_POLL_ID UNIQUE (TELEGRAM_POLL_ID)
);

CREATE TABLE IF NOT EXISTS MATCH_PLAYERS
(
    ID         BIGSERIAL PRIMARY KEY,
    MATCH_ID   BIGINT REFERENCES MATCHES (ID),
    PLAYER_ID  BIGINT REFERENCES PLAYERS (ID),
    PLACE      INTEGER,
    CREATED_AT TIMESTAMPTZ NOT NULL,
    UPDATED_AT TIMESTAMPTZ,
    CONSTRAINT UNQ_MATCH_PLAYER UNIQUE (MATCH_ID, PLAYER_ID)
);
