-- TODO: delete?

CREATE TABLE IF NOT EXISTS EXTERNAL_MESSAGES
(
    ID         BIGSERIAL PRIMARY KEY,
    DTYPE      VARCHAR,
    MESSAGE_ID BIGINT,
    CHAT_ID    BIGINT,
    REPLY_ID   BIGINT,
    POLL_ID    VARCHAR,
    CREATED_AT TIMESTAMPTZ NOT NULL,
    UPDATED_AT TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS PLAYERS
(
    ID                  BIGSERIAL PRIMARY KEY,
    EXTERNAL_ID         BIGINT      NOT NULL,
    EXTERNAL_CHAT_ID    BIGINT      NOT NULL,
    STEAM_NAME          VARCHAR     NOT NULL,
    FIRST_NAME          VARCHAR     NOT NULL,
    LAST_NAME           VARCHAR     NOT NULL,
    EXTERNAL_FIRST_NAME VARCHAR     NOT NULL,
    EXTERNAL_NAME       VARCHAR,
    IS_GUEST BOOLEAN DEFAULT FALSE,
    CREATED_AT          TIMESTAMPTZ NOT NULL,
    UPDATED_AT          TIMESTAMPTZ,
    CONSTRAINT UNQ_EXTERNAL_ID UNIQUE (EXTERNAL_ID),
    CONSTRAINT UNQ_STEAM_NAME UNIQUE (STEAM_NAME)
);

CREATE INDEX IDX_STEAM_NAME ON PLAYERS (STEAM_NAME);

CREATE TABLE IF NOT EXISTS LEADERS
(
    ID         BIGSERIAL PRIMARY KEY,
    NAME       VARCHAR                  NOT NULL,
    MOD_TYPE   VARCHAR                  NOT NULL,
    CREATED_AT TIMESTAMP WITH TIME ZONE NOT NULL,
    UPDATED_AT TIMESTAMP WITH TIME ZONE
);

CREATE TABLE IF NOT EXISTS MATCHES
(
    ID                     BIGSERIAL PRIMARY KEY,
    OWNER_ID               BIGINT REFERENCES PLAYERS (ID),
    MOD_TYPE               VARCHAR                        NOT NULL,
    STATE                  VARCHAR                        NOT NULL,
    POSITIVE_ANSWERS_COUNT INTEGER                        NOT NULL DEFAULT 0,
    SUBMITS_COUNT          INTEGER                        NOT NULL DEFAULT 0,
    SUBMITS_RETRY_COUNT    INTEGER                        NOT NULL DEFAULT 0,
    SCREENSHOT_PATH        VARCHAR,
    FINISH_DATE            DATE,
    LEADER_WON             BIGINT REFERENCES LEADERS (ID) NULL,
    EXTERNAL_POLL_ID       BIGINT REFERENCES EXTERNAL_MESSAGES (ID),
    EXTERNAL_START_ID      BIGINT REFERENCES EXTERNAL_MESSAGES (ID),
    CREATED_AT             TIMESTAMPTZ                    NOT NULL,
    UPDATED_AT             TIMESTAMPTZ,
    CONSTRAINT UNQ_TELEGRAM_POLL_ID UNIQUE (EXTERNAL_POLL_ID)
);

CREATE TABLE IF NOT EXISTS MATCH_PLAYERS
(
    ID                 BIGSERIAL PRIMARY KEY,
    MATCH_ID           BIGINT REFERENCES MATCHES (ID),
    PLAYER_ID          BIGINT REFERENCES PLAYERS (ID),
    EXTERNAL_SUBMIT_ID BIGINT REFERENCES EXTERNAL_MESSAGES (ID),
    PLACE              INTEGER,
    CANDIDATE_PLACE    INTEGER,
    CREATED_AT         TIMESTAMPTZ NOT NULL,
    UPDATED_AT         TIMESTAMPTZ,
    CONSTRAINT UNQ_MATCH_PLAYER UNIQUE (MATCH_ID, PLAYER_ID)
);

CREATE TABLE IF NOT EXISTS SETTINGS
(
    ID         BIGSERIAL PRIMARY KEY,
    KEY        VARCHAR UNIQUE NOT NULL,
    VALUE      VARCHAR,
    CREATED_AT TIMESTAMPTZ    NOT NULL,
    UPDATED_AT TIMESTAMPTZ
);

INSERT INTO SETTINGS (KEY, VALUE, CREATED_AT)
VALUES ('ADMIN_USER_ID', '193506662', CURRENT_TIMESTAMP),
       ('RESUBMITS_LIMIT', '3', CURRENT_TIMESTAMP),
       ('MATCH_START_DELAY', '60', CURRENT_TIMESTAMP),
       ('MONTHLY_MATCHES_THRESHOLD', '15', CURRENT_TIMESTAMP),
       ('FINISH_MATCH_TIMEOUT', '20', CURRENT_TIMESTAMP);

INSERT INTO LEADERS (NAME, MOD_TYPE, CREATED_AT)
VALUES ('Граф Ильбан Ричез', 'CLASSIC', CURRENT_TIMESTAMP),
       ('Тессия Верниус', 'CLASSIC', CURRENT_TIMESTAMP),
       ('Барон Владимир Харконен', 'CLASSIC', CURRENT_TIMESTAMP),
       ('Принцесса Юна Моритани', 'CLASSIC', CURRENT_TIMESTAMP),
       ('Глоссу "Зверь" Раббан', 'CLASSIC', CURRENT_TIMESTAMP),
       ('Герцог Лето Атрейдес', 'CLASSIC', CURRENT_TIMESTAMP),
       ('Пол Атрейдес', 'CLASSIC', CURRENT_TIMESTAMP),
       ('Виконт Хундро Моритани', 'CLASSIC', CURRENT_TIMESTAMP),
       ('Елена Ричез', 'CLASSIC', CURRENT_TIMESTAMP),
       ('Эрцгерцог Арманд Эказ', 'CLASSIC', CURRENT_TIMESTAMP),
       ('Графиня Ариана Торвальд', 'CLASSIC', CURRENT_TIMESTAMP),
       ('Принц Ромбур', 'CLASSIC', CURRENT_TIMESTAMP),
       ('Граф Мемнон Торвальд', 'CLASSIC', CURRENT_TIMESTAMP),
       ('Илеса Эказ', 'CLASSIC', CURRENT_TIMESTAMP),
       ('Гурни Халек', 'UPRISING_4', CURRENT_TIMESTAMP),
       ('Джессика', 'UPRISING_4', CURRENT_TIMESTAMP),
       ('Марго Фенринг', 'UPRISING_4', CURRENT_TIMESTAMP),
       ('Муад''Диб', 'UPRISING_4', CURRENT_TIMESTAMP),
       ('Принцесса Ирулан', 'UPRISING_4', CURRENT_TIMESTAMP),
       ('Стабан Туек', 'UPRISING_4', CURRENT_TIMESTAMP),
       ('Фейд-Раута', 'UPRISING_4', CURRENT_TIMESTAMP),
       ('Шаддам Коррино', 'UPRISING_4', CURRENT_TIMESTAMP),
       ('Эмбер Метулли', 'UPRISING_4', CURRENT_TIMESTAMP);
