CREATE TABLE IF NOT EXISTS LEADERS
(
    ID         BIGSERIAL PRIMARY KEY,
    NAME       VARCHAR                  NOT NULL,
    MOD_TYPE   VARCHAR                  NOT NULL,
    CREATED_AT TIMESTAMP WITH TIME ZONE NOT NULL,
    UPDATED_AT TIMESTAMP WITH TIME ZONE
);

ALTER TABLE MATCHES
    ADD COLUMN LEADER_WON BIGINT REFERENCES LEADERS (ID) NULL;
