INSERT INTO app_settings (key, value, created_at)
VALUES ('ACCEPT_SUBMIT_TIMEOUT', 3, now());

UPDATE app_settings
set key = 'SUBMIT_TIMEOUT_WARNING_NOTIFICATION'
where key = 'FINISH_MATCH_NOTIFICATION_AHEAD_TIMEOUT';

UPDATE app_settings
set key = 'SUBMIT_TIMEOUT'
where key = 'FINISH_MATCH_TIMEOUT';


ALTER TABLE MATCHES
    DROP COLUMN IF EXISTS SUBMITS_COUNT;

ALTER TABLE MATCHES
    ADD COLUMN IF NOT EXISTS SUBMITTER_ID BIGINT REFERENCES PLAYERS (ID);

UPDATE MATCH_PLAYERS
SET EXTERNAL_SUBMIT_ID = NULL;

DELETE
FROM EXTERNAL_MESSAGES EM
WHERE EM.ID IN (SELECT EXTERNAL_SUBMIT_ID FROM MATCH_PLAYERS MP);

ALTER TABLE match_players
    DROP COLUMN IF EXISTS EXTERNAL_SUBMIT_ID;
