INSERT INTO app_settings (key, value, created_at)
VALUES ('ACCEPT_SUBMIT_TIMEOUT', 3, now());

UPDATE app_settings
set key = 'SUBMIT_TIMEOUT_WARNING_NOTIFICATION'
where key = 'FINISH_MATCH_NOTIFICATION_AHEAD_TIMEOUT';

UPDATE app_settings
set key = 'SUBMIT_TIMEOUT'
where key = 'FINISH_MATCH_TIMEOUT';


ALTER TABLE MATCHES
    DROP COLUMN IF EXISTS SUBMITS_COUNT;
