DELETE FROM MATCHES;
DELETE FROM MATCH_PLAYERS;
DELETE FROM PLAYERS;

INSERT INTO PLAYERS (ID, TELEGRAM_ID, STEAM_NAME, FIRST_NAME, LAST_NAME, USER_NAME, CREATED_AT)
VALUES (1, 1, 'st_AKos', 'Alex', 'Kos', 'tg_AKos', '2010-01-10');
INSERT INTO PLAYERS (ID, TELEGRAM_ID, STEAM_NAME, FIRST_NAME, LAST_NAME, USER_NAME, CREATED_AT)
VALUES (2, 2, 'st_PVas', 'Petr', 'Vas', 'tg_PVas', '2010-02-11');
INSERT INTO PLAYERS (ID, TELEGRAM_ID, STEAM_NAME, FIRST_NAME, LAST_NAME, USER_NAME, CREATED_AT)
VALUES (3, 3, 'st_ARak', 'Anna', 'Rak', 'tg_ARak', '2010-03-09');
INSERT INTO PLAYERS (ID, TELEGRAM_ID, STEAM_NAME, FIRST_NAME, LAST_NAME, USER_NAME, CREATED_AT)
VALUES (4, 4, 'st_SBin', 'Svetlana', 'Bin', 'tg_SBin', '2010-04-08');
